### ISSUE TITLE
Create unit tests for Order Details, Order Row and Order List components

### ISSUE THREAD

**Issue by lucastfa** [leandroalonso/uaifood-mobile#13]
Using Enzyme and the structure we already have create unit tests for all the componentes we have in:

- Order Details
- Order Row
- Order List

**Comment by andreyleonardo** [comment]
We've created the missing test for Order Details and Order Row. 
To test Order List and App, we'll need to define the pattern that we want to use first (e.g. Redux or Flux) 'cause we need to mock the API call and only after have the pattern defined we'll be able to mock the actions.

**Comment by andreyleonardo** [comment]
Done.
