### ISSUE TITLE
Update Readme with iOS project setup

### ISSUE THREAD

**Issue by andreyleonardo** [leandroalonso/uaifood-mobile#19]
Needs to add to readme how to setup the project for iOS.

**Comment by andreyleonardo** [comment]
Done.
Se alguém puder revisar e indicar mudanças e correções. =)

**Comment by macecchi** [comment]
Parece ok pra mim!

Eu alteraria umas coisas do markdown, como algumas coisas que tão entre ` mas não são código e colocar os links em links mesmo, ao invés de código também.

...mas fica pra outra hora :P
